{{- if .Values.podDisruptionBudget.backend.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "elasticguard.backend.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "elasticguard.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  minAvailable: {{ .Values.podDisruptionBudget.backend.minAvailable }}
  selector:
    matchLabels:
      {{- include "elasticguard.componentLabels" (list "backend" .) | nindent 6 }}
{{- end }}
---
{{- if .Values.podDisruptionBudget.frontend.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "elasticguard.frontend.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "elasticguard.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  minAvailable: {{ .Values.podDisruptionBudget.frontend.minAvailable }}
  selector:
    matchLabels:
      {{- include "elasticguard.componentLabels" (list "frontend" .) | nindent 6 }}
{{- end }}
